force-app/main/default/objects/Team__c/Team__c.object-meta.xml
<CustomObject>
	<description>This represents a team collection</description>
	<label>Team</label>
	<nameField>
		<label>Name</label>
		<type>Text</type>
	</nameField>
	<pluralLabel>Teams</pluralLabel>
	<sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Team_Member__c/Team_Member__c.object-meta.xml
<CustomObject>
	<description>Represents a member belonging to a Team</description>
	<label>Team Member</label>
	<nameField>
		<label>Name</label>
		<type>Text</type>
	</nameField>
	<pluralLabel>Team Members</pluralLabel>
	<sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Team_Member__c/fields/Skills__c.field-meta.xml
<CustomField>
	<fullName>Skills__c</fullName>
	<description>Comma separated values of Skills set</description>
	<label>Skills</label>
	<length>255</length>
	<type>Text</type>
</CustomField>

force-app/main/default/objects/Team_Member__c/fields/Team__c.field-meta.xml
<CustomField>
	<fullName>Team__c</fullName>
	<description>The team to which this member belongs to.</description>
	<inlineHelpText>The team to which this member belongs to.</inlineHelpText>
	<label>Team</label>
	<referenceTo>Team__c</referenceTo>
	<relationshipLabel>Team Members</relationshipLabel>
	<relationshipName>Team_Members</relationshipName>
	<relationshipOrder>0</relationshipOrder>
	<type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/TeamListController.cls
public class TeamListController {

	public TeamListController() {

	}
	
	@AuraEnabled
	public static List<SObject> getMemberRecords(Id teamId) {
		Integer limitOfRecords = Limits.getLimitDmlRows();

		// Adding query for tem members
		String query = 'SELECT Id, Name, Skills__c, Team__r.Name FROM Team_Member__c WHERE Team__c = :teamId ORDER BY Name LIMIT :limitOfRecords';
		return Database.query(query);
	}

}