force-app/main/default/objects/Team__c/Team__c.object-meta.xml
<CustomObject>
	<description>This represents a team collection</description>
	<label>Team</label>
	<nameField>
		<label>Name</label>
		<type>Text</type>
	</nameField>
	<pluralLabel>Teams</pluralLabel>
	<sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Team_Member__c/Team_Member__c.object-meta.xml
<CustomObject>
	<description>Represents a member belonging to a Team</description>
	<label>Team Member</label>
	<nameField>
		<label>Name</label>
		<type>Text</type>
	</nameField>
	<pluralLabel>Team Members</pluralLabel>
	<sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Team_Member__c/fields/Skills__c.field-meta.xml
<CustomField>
	<fullName>Skills__c</fullName>
	<description>Comma separated values of Skills set</description>
	<label>Skills</label>
	<length>255</length>
	<type>Text</type>
</CustomField>

force-app/main/default/objects/Team_Member__c/fields/Team__c.field-meta.xml
<CustomField>
	<fullName>Team__c</fullName>
	<description>The team to which this member belongs to.</description>
	<inlineHelpText>The team to which this member belongs to.</inlineHelpText>
	<label>Team</label>
	<referenceTo>Team__c</referenceTo>
	<relationshipLabel>Team Members</relationshipLabel>
	<relationshipName>Team_Members</relationshipName>
	<relationshipOrder>0</relationshipOrder>
	<type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/TeamListControllerTest.cls
@isTest
private class TeamListControllerTest {
	static final Integer NUMBER_OF_TEAM_MEMBERS = 5;

	@isTest
	static void testGetMemberRecords_teamRecordId_getAllTeamMembers() {
		// Given
		Team__c team = new Team__c(Name = 'Test Team');
		insert team;
		List<Team_Member__c> memberList = new List<Team_Member__c>();
		for(Integer index = 0; index < NUMBER_OF_TEAM_MEMBERS; index++) {
			memberList.add(new Team_Member__c(
				Name = 'Test Team Member ' + index,
				Team__c = team.Id,
				Skills__c = 'Skill ' + index
			));
		}
		insert memberList;

		// When
		Test.startTest();
		List<SObject> teamMembers = TeamListController.getMemberRecords(team.Id);
		Test.stopTest();

		// Then
		System.assertEquals(NUMBER_OF_TEAM_MEMBERS, teamMembers.size(), 'Should fetch all the team members');
		Boolean isMemberOfTeam = true;
		for(SObject obj : teamMembers) {
			if(team.Id != obj.get('Team__c')) {
				isMemberOfTeam = false;
				break;
			}
		}
		System.assert(isMemberOfTeam, 'All team members should belong to team for which they are fetched');
	}
}